version: '2.1'
services:
  bot:
    build: ./bot
    command: python run.py
    volumes:
      - ./bot:/code
    depends_on:
      db:
        condition: service_healthy
      tg-cli:
        condition: service_healthy
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "db"]
      interval: 30s
      timeout: 10s
      retries: 5
  tg-cli:
    build: ./tg-cli
    command: ["/bin/telegram-cli", "--json", "-P", "4458", "--accept-any-tcp", "--disable-readline", "--config", "/telegram/config.cfg"]
    volumes:
      - ./storage/tg-cli:/telegram/data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "tg-cli"]
      interval: 30s
      timeout: 10s
      retries: 5
