version: '2.1'
services:
  bot:
    build: ./bot
    command: ["python", "-u", "run.py"]
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./storage/bot:/code/storage
    depends_on:
      tg-cli:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    restart: unless-stopped
  tg-cli:
    build: ./tg-cli
    volumes:
      - ./storage/tg-cli:/telegram
    depends_on:
      rabbit:
        condition: service_healthy
    restart: unless-stopped
  db:
    build: ./db
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    restart: unless-stopped
  rabbit:
    build: ./rabbitmq
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
